bind_mounts:
- container_path: /nfs
  host_path: /nfs
  propagation: rprivate
  read_only: false
debug: false
description: example-shell-custom-demo1
environment:
  force_pull_image: false
  image:
    cpu: harbor.vhio.net/determine/custom_cpu:0.24.1.7
    cuda: harbor.vhio.net/determine/custom_gpu:0.24.1.7
resources:
  devices: null
  # Default CPU: CPU | Default GPU: GPU | AMD CPU AMD
  resource_pool: CPU
  slots: 1
  weight: 1
work_dir: null
