bind_mounts:
- container_path: /nfs
  host_path: /nfs
  propagation: rprivate
  read_only: false
debug: false
description: kmilo-shell-custom-demo1
labels:
  - kmilo
  - shell
environment:
  force_pull_image: false
  image:
    cpu: harbor.vhio.net/determine/custom_cpu:0.24.0.3
    cuda: harbor.vhio.net/determine/custom_gpu:0.24.0.3
resources:
  devices: null
  # Default CPU: default-i7cpu | Default GPU: i9-rtx3090-gpu | AMD CPU: amd-cpu | GPU 4090: amd-rtx4090-gpu | i9 CPU: i9-cpu
  resource_pool: default-i7cpu
  slots: 1
  weight: 1
work_dir: null
