bind_mounts:
- container_path: /nfs
  host_path: /nfs
  propagation: rprivate
  read_only: false
debug: false
description: example-rdesktop-demo1
entrypoint: null
environment:
  add_capabilities: 
    - SYS_ADMIN
    - DAC_READ_SEARCH
  drop_capabilities: null
  environment_variables: 
# You have to open the browser using the same password
# the user is: kasm_user
    - VNC_PW=password2
  force_pull_image: false
  image:
    cpu: harbor.vhio.net/desktop:0.0.1
    cuda: harbor.vhio.net/desktop:0.0.1
  pod_spec: null
  ports: null
  proxy_ports:
    - proxy_port: 6901
      proxy_tcp: true
      unauthenticated: true
idle_timeout: null
notebook_idle_type: kernels_or_terminals
pbs: {}
resources:
  devices: null
  # Default CPU: CPU | Default GPU: GPU | AMD CPU AMD
  resource_pool: CPU1
  slots: 1
  weight: 1
  shm_size: 2GiB
slurm: {}
work_dir: null
