bind_mounts:
- container_path: /nfs
  host_path: /nfs
  propagation: rprivate
  read_only: false
debug: false
description: kmilo-cmd-demo1
entrypoint: null
environment:
  add_capabilities: null
  drop_capabilities: null
  force_pull_image: false
  image:
    cpu: harbor.vhio.net/determine/custom_cpu:0.24.1.0
    cuda: harbor.vhio.net/determine/custom_gpu:0.24.1.0
    rocm: determinedai/environments:rocm-5.0-pytorch-1.10-tf-2.7-rocm-0.24.0
  pod_spec: null
  ports: null
  proxy_ports: null
idle_timeout: null
notebook_idle_type: kernels_or_terminals
pbs: {}
resources:
  devices: null
  # Default CPU: default-i7cpu | Default GPU: RTX_X090-gpu | AMD CPU .34: amd-cpu-64 | AMD CPU .1.26: amd-cpu-128 | i9 CPU: i9-cpu
  resource_pool: default-i7cpu
  slots: 1
  weight: 1
slurm: {}
work_dir: null
