bind_mounts:
- container_path: /nfs
  host_path: /nfs
  propagation: rprivate
  read_only: false
- container_path: /var/run/docker.sock
  host_path: /var/run/docker.sock
  propagation: rprivate
  read_only: false
debug: false
description: example-shell-custom-add-caps
environment:
# check https://docs.docker.com/engine/containers/run/#runtime-privilege-and-linux-capabilities
  add_capabilities:
    - SYS_ADMIN
    - DAC_READ_SEARCH
  force_pull_image: false
  image:
    cpu: harbor.vhio.net/determine/custom_cpu:1.0.0.3
    cuda: harbor.vhio.net/determine/custom_gpu:1.0.0.3
resources:
  devices: null
  # Default CPU: CPUryzen | Default GPU: RTX_4080S | AMD CPUryzen CPUi9 RTX_4080S RTX_X090
  resource_pool: RTX_4080S
  slots: 1
  weight: 1
  shm_size: 4GiB
work_dir: null
