bind_mounts:
- container_path: /nfs
  host_path: /nfs
  propagation: rprivate
  read_only: false
debug: false
description: kmilo-shell-custom-add-caps
environment:
  add_capabilities: 
    - SYS_ADMIN
    - DAC_READ_SEARCH
  force_pull_image: false
  image:
    cpu: harbor.vhio.net/determine/custom_cpu:0.24.0.7
    cuda: harbor.vhio.net/determine/custom_gpu:0.24.0.7
resources:
  devices: null
  # Default CPU: default-i7cpu | Default GPU: RTX_X090-gpu | AMD CPU .34: amd-cpu-64 | AMD CPU .1.26: amd-cpu-128 | i9 CPU: i9-cpu
  resource_pool: amd-cpu-64
  slots: 1
  weight: 1
  shm_size: 4GiB
work_dir: null
