bind_mounts:
- container_path: /nfs
  host_path: /nfs
  propagation: rprivate
  read_only: false
- container_path: /var/run/docker.sock
  host_path: /var/run/docker.sock
  propagation: rprivate
  read_only: false
debug: false
description: example-shell-custom-add-caps
environment:
# check https://docs.docker.com/engine/containers/run/#runtime-privilege-and-linux-capabilities
  add_capabilities:
    - SYS_ADMIN
    - DAC_READ_SEARCH
  force_pull_image: false
  image:
    cpu: harbor.vhio.net/determine/custom_cpu:0.24.1.8
    cuda: harbor.vhio.net/determine/custom_gpu:0.24.1.8
resources:
  devices: null
  # Default CPU: CPU | Default GPU: GPU | AMD CPU AMD
  resource_pool: RTX_X090
  slots: 1
  weight: 1
  shm_size: 4GiB
work_dir: null
