bind_mounts:
- container_path: /nfs
  host_path: /nfs
  propagation: rprivate
  read_only: false
debug: false
description: example-rtools-demo1
entrypoint: null
environment:
  add_capabilities: 
    - SYS_ADMIN
    - DAC_READ_SEARCH
  drop_capabilities: null
  environment_variables: 
    - RESOLUTION=1920x1080
    - SLACK_URL=https://hooks.slack.com/services/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
# You have to open the browser using the same password
# http://localhost:6080/vnc.html?password=demo1234&autoconnect=true&resize=remote
# If you don't set the env variable the the default password is matlab
    - DEFAULT_VNC_PASSWORD=demo1234
  force_pull_image: false
  image:
    cpu: harbor.vhio.net/determine/srtools:0.24.5
    cuda: harbor.vhio.net/determine/srtools:0.24.5
  pod_spec: null
  ports: null
  proxy_ports:
    - proxy_port: 5901
      proxy_tcp: true
      unauthenticated: true
    - proxy_port: 6080
      proxy_tcp: true
      unauthenticated: true
idle_timeout: null
notebook_idle_type: kernels_or_terminals
pbs: {}
resources:
  devices: null
  # Default CPU: CPU | Default GPU: GPU | AMD CPU AMD
  resource_pool: CPU1
  slots: 1
  weight: 1
  shm_size: 8GiB
slurm: {}
work_dir: null
