bind_mounts:
- container_path: /nfs
  host_path: /nfs
  propagation: rprivate
  read_only: false
- container_path: /var/run/docker.sock
  host_path: /var/run/docker.sock
  propagation: rprivate
  read_only: false
debug: false
description: example-shell-vscode-web
environment:
  add_capabilities: 
    - SYS_ADMIN
    - DAC_READ_SEARCH
  drop_capabilities: null
  environment_variables: 
    - PASSWORD=demo1234
# This ENV set the path to store the vscode settings.
    - HOMECONFIG=/nfs/home
  force_pull_image: false
  image:
    cpu: harbor.vhio.net/determine/custom_cpu:0.24.2.4
    cuda: harbor.vhio.net/determine/custom_gpu:0.24.2.4
  pod_spec: null
  ports: null
  proxy_ports:
    - proxy_port: 8080
      proxy_tcp: true
      unauthenticated: true
resources:
  devices: null
  # Default CPU: CPUryzen | Default GPU: RTX_4080S | AMD CPUryzen CPUi9 RTX_4080S RTX_X090
  resource_pool: CPUryzen
  slots: 1
  weight: 1
  shm_size: 4GiB
work_dir: null
