bind_mounts:
- container_path: /nfs
  host_path: /nfs
  propagation: rprivate
  read_only: false
debug: false
description: example-shell-R-Jupyter
environment:
  force_pull_image: false
  image:
    cpu: harbor.vhio.net/determine/custom_cpu:1.0.0.3
    cuda: harbor.vhio.net/determine/custom_gpu:1.0.0.3
resources:
  devices: null
  # Default CPU: CPUryzen | Default GPU: RTX_4080S | AMD CPUryzen CPUi9 RTX_4080S RTX_X090
  resource_pool: CPUryzen
  slots: 1
  weight: 1
work_dir: null
