bind_mounts:
- container_path: /nfs
  host_path: /nfs
  propagation: rprivate
  read_only: false
debug: false
description: example-rtools-demo1
entrypoint: null
environment:
  drop_capabilities: null
  force_pull_image: false
  image:
    cpu: harbor.vhio.net/determine/srtools:0.24.5
  pod_spec: null
idle_timeout: null
notebook_idle_type: kernels_or_terminals
pbs: {}
resources:
  devices: null
  # Default CPU: CPU | Default GPU: GPU | AMD CPU AMD
  resource_pool: CPU1
slurm: {}
work_dir: null
