bind_mounts:
- container_path: /nfs
  host_path: /nfs
  propagation: rprivate
  read_only: false
debug: false
description: kmilo-rtools-demo1
entrypoint: null
environment:
  drop_capabilities: null
  force_pull_image: false
  image:
    cpu: harbor.vhio.net/determine/srtools:0.24.4
  pod_spec: null
idle_timeout: null
notebook_idle_type: kernels_or_terminals
pbs: {}
resources:
  devices: null
  # Default CPU: default-i7cpu | Default GPU: RTX_X090-gpu | AMD CPU .34: amd-cpu-64 | AMD CPU .1.26: amd-cpu-128 | i9 CPU: i9-cpu
  resource_pool: amd-cpu-64
slurm: {}
work_dir: null
